import {
  MoonIcon,
  SunIcon,
  TextAlignLeftIcon,
  TextAlignCenterIcon,
  TextAlignRightIcon,
  CircleIcon,
  CheckIcon,
  CaretSortIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  Pencil1Icon,
  TrashIcon,
} from "@radix-ui/react-icons";

import {
  Home,
  Bell,
  Settings,
  User,
  Mail,
  Inbox,
  Sun,
  Moon,
  ShieldCheck,
  ChevronLeft,
  ChevronRight,
  Menu,
  Plus,
  Send,
  List,
  ClipboardCheck,
  Clipboard,
  Clock,
  Building2,
  Calendar,
  CheckCircle,
  Briefcase,
  Type,
  Activity,
  Upload,
  CheckSquare,
  Info,
  FileText,
  Trash2,
  FilePlus,
  X,
  AlertCircle,
  UploadCloud,
  ShieldAlert,
  File,
  MessageSquare,
  Download,
  Eye,
  Search,
  CheckCircle2,
  XCircle,
  RefreshCcw,
  RefreshCw,
  Circle,
  Globe,
  MessageCircle,
  FileType,
  Lock,
  LogOut,
  CreditCard,
  ChevronsDown,
  ChevronsUp,
  Languages,
  Loader2,
  History,
  LayoutGrid,
  Filter,
  Check,
  BarChart4,
  Monitor,
} from "lucide-react";

export const RadixIcons = {
  MoonIcon,
  SunIcon,
  TextAlignLeftIcon,
  TextAlignCenterIcon,
  TextAlignRightIcon,
  CircleIcon,
  CheckIcon,
  CaretSortIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  Pencil1Icon,
  TrashIcon,
};

export const MaterialIcons = {
  Home,
  Mail,
  Inbox: Inbox,
  Settings,
  NotificationsOutlined: Bell,
  SettingsOutlined: Settings,
  PersonOutlined: User,
  LightModeOutlined: Sun,
  DarkModeOutlined: Moon,
  AdminPanelSettings: ShieldCheck,
  ChevronLeft,
  ChevronRight,
  Menu,
  Add: Plus,
  Send,
  List,
  AssignmentTurnedIn: ClipboardCheck,
  Assignment: Clipboard,
  PendingActions: Clock,
  Person: User,
  Business: Building2,
  Notifications: Bell,
  Schedule: Calendar,
  CheckCircle,
  Work: Briefcase,
  Input: Type,
  DirectionsRun: Activity,
  Upload,
  Beenhere: CheckSquare,
  Info,
  Notes: FileText,
  Summarize: FileText,
  Delete: Trash2,
  ExpandMore: ChevronDownIcon,
  NotificationImportant: AlertCircle,
  Cancel: X,
  FileUpload: UploadCloud,
  LocalPolice: ShieldAlert,
  FilePresent: File,
  Feedback: MessageSquare,
  Download,
  Visibility: Eye,
  SearchOutlined: Search,
  Search,
  Checklist: ClipboardCheck,
  HomeOutlined: Home,
  CheckCircleOutline: CheckCircle2,
  HighlightOffOutlined: XCircle,
  Cached: RefreshCcw,
  Loop: RefreshCw,
  RadioButtonUnchecked: Circle,
  Language: Globe,
  Chat: MessageCircle,
  Description: FileText,
  Lock,
  Logout: LogOut,
  CreditCard,
  KeyboardArrowDown: ChevronsDown,
  KeyboardArrowUp: ChevronsUp,
  Translate: Languages,
  Pending: Loader2,
  Timeline: History,
  ViewWeek: LayoutGrid,
  FilterList: Filter,
  ViewHeadline: List,
  Check,
  WorkOutline: Briefcase,
  Assessment: BarChart4,
  Monitor: Monitor, // Added for Dashboard if needed
  Users: User, // Added alias for consistency
};
