/**
 * AWS Configuration Helper
 *
 * This module provides AWS configuration that works in both local development
 * and production (Amplify) environments.
 *
 * In production, Amplify automatically provides AWS credentials via IAM roles.
 * In local development, credentials are read from environment variables.
 */

import outputs from "@/amplify_outputs.json";

/**
 * AWS Configuration Helper
 *
 * This module provides AWS configuration that works in both local development
 * and production (Amplify) environments.
 *
 * It reads directly from amplify_outputs.json which is generated by:
 * - npx ampx sandbox (Local)
 * - Amplify CI/CD (Production)
 */

export const getAWSRegion = () => {
  return outputs.auth?.aws_region || process.env.NEXT_PUBLIC_AWS_REGION || "us-east-1";
};

export const getUserPoolId = () => {
  return outputs.auth?.user_pool_id || process.env.AMPLIFY_AUTH_USERPOOL_ID || "";
};

export const getAWSCredentials = () => {
  // 1. Check for manual overrides (User requested "APP_" prefix)
  if (process.env.APP_AWS_ACCESS_KEY_ID && process.env.APP_AWS_SECRET_ACCESS_KEY) {
    return {
      accessKeyId: process.env.APP_AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.APP_AWS_SECRET_ACCESS_KEY,
      sessionToken: process.env.APP_AWS_SESSION_TOKEN,
    };
  }

  // 2. Check for standard environment variables (Local use or explicitly set in console)
  // IMPORTANT: Must include sessionToken if present (required for IAM Role / Temporary Creds)
  if (process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY) {
    return {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      sessionToken: process.env.AWS_SESSION_TOKEN,
    };
  }

  // 3. Return undefined to allow SDK's default provider chain (EC2/Lambda Instance Profile etc.)
  return undefined;
};

export const getCognitoClientConfig = () => {
  return {
    region: getAWSRegion(),
    credentials: getAWSCredentials(),
  };
};

export const getDynamoDBClientConfig = () => {
  return {
    region: getAWSRegion(),
    credentials: getAWSCredentials(),
  };
};

export const getS3ClientConfig = () => {
  return {
    region: getAWSRegion(),
    credentials: getAWSCredentials(),
  };
};

/**
 * Get DynamoDB table name for Companies
 * (Reading from env vars as table names might not be in standard outputs unless customized)
 */
export const getCompanyTableName = () => {
  return process.env.DYNAMODB_COMPANY_TABLE || "";
};

/**
 * Get DynamoDB table name for Incident Reports
 */
export const getIncidentReportTableName = () => {
  return process.env.DYNAMODB_INCIDENT_REPORT_TABLE || "";
};

/**
 * Get S3 bucket name for photo uploads
 */
export const getS3BucketName = () => {
  return (outputs.storage as any)?.bucket_name || process.env.S3_BUCKET_NAME || "";
};
