/**
 * AWS Configuration Helper
 *
 * This module provides AWS configuration that works in both local development
 * and production (Amplify) environments.
 *
 * In production, Amplify automatically provides AWS credentials via IAM roles.
 * In local development, credentials are read from environment variables.
 */

import outputs from "@/amplify_outputs.json";

/**
 * AWS Configuration Helper
 *
 * This module provides AWS configuration that works in both local development
 * and production (Amplify) environments.
 *
 * It reads directly from amplify_outputs.json which is generated by:
 * - npx ampx sandbox (Local)
 * - Amplify CI/CD (Production)
 */

export const getAWSRegion = () => {
  return outputs.auth?.aws_region || process.env.NEXT_PUBLIC_AWS_REGION || "us-east-1";
};

export const getUserPoolId = () => {
  return outputs.auth?.user_pool_id || process.env.AMPLIFY_AUTH_USERPOOL_ID || "";
};

export const getAWSCredentials = () => {
  // In production (Amplify), credentials are provided automatically via IAM roles
  // Only use explicit credentials for local development if really needed and not provided by sandbox
  if (process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY) {
    return {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    };
  }
  // Return undefined to use default credential provider chain (IAM roles in production)
  return undefined;
};

export const getCognitoClientConfig = () => {
  return {
    region: getAWSRegion(),
    credentials: getAWSCredentials(),
  };
};

export const getDynamoDBClientConfig = () => {
  return {
    region: getAWSRegion(),
    credentials: getAWSCredentials(),
  };
};

export const getS3ClientConfig = () => {
  return {
    region: getAWSRegion(),
    credentials: getAWSCredentials(),
  };
};

/**
 * Get DynamoDB table name for Companies
 * (Reading from env vars as table names might not be in standard outputs unless customized)
 */
export const getCompanyTableName = () => {
  return process.env.DYNAMODB_COMPANY_TABLE || "";
};

/**
 * Get DynamoDB table name for Incident Reports
 */
export const getIncidentReportTableName = () => {
  return process.env.DYNAMODB_INCIDENT_REPORT_TABLE || "";
};

/**
 * Get S3 bucket name for photo uploads
 */
export const getS3BucketName = () => {
  return (outputs.storage as any)?.bucket_name || process.env.S3_BUCKET_NAME || "";
};
